name: treemap_ui
version: 0.2.0
description: A generic treemap user interface component for web applications.
author: Uwe Sommerlatt <uwe.sommerlatt@gmail.com>
dependencies:
  browser: any
dev_dependencies:
  unittest: any
